it is only a copy of RIDE fork(https://github.com/crylearner/RIDE), which give a befenit for searching this project.
this fork support python3.x and wxpython4.0.b. 
at present, it is only a beta version and still in developing.
